package com.inmobia.axiata.web.beans;

public enum MessageType {
	WINNER_TEXT,LOSER_TEXT,SECOND_HOUR_TEASER,FOURTH_HOUR_TEASER,SIXTH_HOUR_TEASER,INFO,HELP,DAILY_QUESTION_QUOTA_REACHED,LAST_QUESTION_WRONG,LAST_QUESTION_CORRECT,CONTINUITY_CONFIRMATION,WELCOME_MESSAGE, CORRECT_ANSWER, WRONG_ANSWER, STOP_MESSAGE, WELCOME_BACK_MESSAGE, POINTS_REQUEST, RUSH_HOUR_START, REGISTRATION_FAILURE, REGISTER_FIRST, NO_MORE_QUESTIONS, WELCOME_BACK, BLACKLISTED, FIRST_TEASER, OTHER_TEASER, HIGH_TEASER, HAPPY_HOUR_WRONG_ANSWER, HAPPY_HOUR_CORRECT_ANSWER, HAPPY_HOUR_START, HAPPY_HOUR_STOP, WRONG_RESPONSE, CONFIRMATION_MESSAGE, CONTINUITY_MESSAGE_AFTER_AFTER_SET_OF_QUESTIONS, CONFIRM_FIRST, LANGUAGE_CHANGED, CANNOT_PLAY_DUE_TO_CAPPING, CHOOSE_LANGUAGE_FIRST, DAILY_CONFIRMATION, NAME_CHANGED, PRE_WELCOME_MESSAGE, POST_WELCOME_MESSAGE, PRE_SELECTION_NOTIFICATION, PLAY_TOMORROW_CAP_REACHED, INSUFFICIENT_BALANCE,TRIVIA_ENDED, RANDOM_NUMBER_NOTIFICATION, WINNER_MESSAGE, NON_WINNER_MESSAGE, UNSUBSCRIBED_SINGLE_SERVICE_ADVICE, UNABLE_TO_UNSUBSCRIBE_ADVICE, INDIVIDUAL_UNSUBSCRIBE_ADVICE, NOT_SUBSCRIBED_TO_ANY_SERVICE_ADVICE, ALREADY_SUBSCRIBED_ADVICE, UNKNOWN_KEYWORD_ADVICE, ALL_SERVICES,DOUBLE_CONFIRMATION_ADVICE, VALIDATION_CONFIRMATION_ADVICE, MSISDN_CHECK_NOTIFICATION 
;
	
	public static MessageType get(String langst){
		
		MessageType message_key = null;//Language.ENGLISH;
		
		if(langst!=null)
			if(langst.isEmpty())
				return message_key;
		
		langst = langst.trim().toUpperCase();
		
		if(langst.equals("INFO") )
			message_key = MessageType.INFO;
		if(langst.equals("HELP"))
			message_key = MessageType.HELP;
		if(langst.equals("SECOND_HOUR_TEASER"))
			message_key = MessageType.SECOND_HOUR_TEASER;
		if(langst.equals("FOURTH_HOUR_TEASER"))
			message_key = MessageType.FOURTH_HOUR_TEASER;
		if(langst.equals("SIXTH_HOUR_TEASER"))
			message_key = MessageType.SIXTH_HOUR_TEASER;
		if(langst.equals("TRIVIA_ENDED"))
			message_key = MessageType.TRIVIA_ENDED;
		if(langst.equals("WINNER_TEXT"))
			message_key = MessageType.WINNER_TEXT;
		if(langst.equals("LOSER_TEXT"))
			message_key = MessageType.LOSER_TEXT;
		if(langst.equals("RANDOM_NUMBER_NOTIFICATION"))
			message_key = MessageType.RANDOM_NUMBER_NOTIFICATION;
		if(langst.equals("WINNER_MESSAGE"))
			message_key = MessageType.WINNER_MESSAGE;
		if(langst.equals("LOSER_MESSAGE"))
			message_key = MessageType.NON_WINNER_MESSAGE;
		if(langst.equals("UNSUBSCRIBED_SINGLE_SERVICE_ADVICE"))
			message_key = MessageType.UNSUBSCRIBED_SINGLE_SERVICE_ADVICE;
		if(langst.equals("UNABLE_TO_UNSUBSCRIBE_ADVICE"))
			message_key = MessageType.UNABLE_TO_UNSUBSCRIBE_ADVICE;
		if(langst.equals("INDIVIDUAL_UNSUBSCRIBE_ADVICE"))
			message_key = MessageType.INDIVIDUAL_UNSUBSCRIBE_ADVICE;
		if(langst.equals("NOT_SUBSCRIBED_TO_ANY_SERVICE_ADVICE"))
			message_key = MessageType.NOT_SUBSCRIBED_TO_ANY_SERVICE_ADVICE;
		if(langst.equals("ALREADY_SUBSCRIBED_ADVICE"))
			message_key = MessageType.ALREADY_SUBSCRIBED_ADVICE;
		if(langst.equals("UNKNOWN_KEYWORD_ADVICE"))
			message_key = MessageType.UNKNOWN_KEYWORD_ADVICE;
		if(langst.equals("ALL_SERVICES"))
			message_key = MessageType.ALL_SERVICES;
		if(langst.equals("DOUBLE_CONFIRMATION_ADVICE"))
			message_key = MessageType.DOUBLE_CONFIRMATION_ADVICE;
		if(langst.equals("VALIDATION_CONFIRMATION_ADVICE"))
			message_key = MessageType.VALIDATION_CONFIRMATION_ADVICE;
		if(langst.equals("MSISDN_CHECK_NOTIFICATION"))
			message_key = MessageType.MSISDN_CHECK_NOTIFICATION;
		
		
		//TODO, map the rest!
		
		return message_key;
		
		
	}
}
