package com.pixelandtag.api;

public enum BillingStatus {

	OPERATOR_ALREADY_BILLED_ON_MO, OPERATOR_TO_BILL_ON_MT, NO_BILLING_REQUIRED,WAITING_BILLING,BILLING_INPROGRESS,SUCCESSFULLY_BILLED,BILLING_FAILED,BILLING_FAILED_PERMANENTLY, INSUFFICIENT_FUNDS;
}
