package com.pixelandtag.api;

public enum BillingStatus {

	NO_BILLING_REQUIRED,WAITING_BILLING,BILLING_INPROGRESS,SUCCESSFULLY_BILLED,BILLING_FAILED,BILLING_FAILED_PERMANENTLY, INSUFFICIENT_FUNDS;
}
